### ISSUE TITLE
Error: Attempted to enable semantics without configuring an onSemanticsUpdate callback.

### ISSUE THREAD

**Issue by adil192** [kekland/simulator#1]
Calling `SimulatorWidgetsFlutterBinding.ensureInitialized()` gives me this error:
```console
ahann@fedora:~/Documents/GitHub/saber$ flutter run -t lib/main_simulated.dart -d linux
Launching lib/main_simulated.dart on Linux in debug mode...
Building Linux application...                                           
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/rendering/object.dart': Failed assertion: line 1254 pos 16: 'onSemanticsUpdate != null': Attempted to enable semantics without configuring an onSemanticsUpdate callback.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      PipelineOwner._updateSemanticsOwner (package:flutter/src/rendering/object.dart:1254:16)
#3      PipelineOwner.attach (package:flutter/src/rendering/object.dart:1358:5)
#4      RendererBinding.initInstances (package:flutter/src/rendering/binding.dart:51:23)
#5      WidgetsBinding.initInstances (package:flutter/src/widgets/binding.dart:344:11)
#6      PointerListenerExtractorBinding.initInstances (package:simulator/src/bindings/pointer_listener_extractor.dart:11:11)
#7      AppImageExtractorBinding.initInstances (package:simulator/src/bindings/app_image_extractor.dart:11:11)
#8      MobileGestureSimulatorBinding.initInstances (package:simulator/src/bindings/mobile_gesture_simulator.dart:12:11)
#9      new BindingBase (package:flutter/src/foundation/binding.dart:154:5)
#10     new _SimulatorWidgetsFlutterBinding&BindingBase&GestureBinding (package:simulator/src/bindings/widgets_binding.dart)
#11     new _SimulatorWidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding (package:simulator/src/bindings/widgets_binding.dart)
#12     new _SimulatorWidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding (package:simulator/src/bindings/widgets_binding.dart)
#13     new _SimulatorWidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding&PaintingBinding (package:simulator/src/bindings/widgets_binding.dart)
#14     new _SimulatorWidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding&PaintingBinding&SemanticsBinding (package:simulator/src/bindings/widgets_binding.dart)
#15     new _SimulatorWidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding&PaintingBinding&SemanticsBinding&RendererBinding (package:simulator/src/bindings/widgets_binding.dart)
#16     new _SimulatorWidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding (package:simulator/src/bindings/widgets_binding.dart)
#17     new _SimulatorWidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding&PointerListenerExtractorBinding (package:simulator/src/bindings/widgets_binding.dart)
#18     new _SimulatorWidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding&PointerListenerExtractorBinding&SystemUiChromeExtractorBinding (package:simulator/src/bindings/widgets_binding.dart)
#19     new _SimulatorWidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding&PointerListenerExtractorBinding&SystemUiChromeExtractorBinding&AppImageExtractorBinding (package:simulator/src/bindings/widgets_binding.dart)
#20     new _SimulatorWidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding&PointerListenerExtractorBinding&SystemUiChromeExtractorBinding&AppImageExtractorBinding&MobileGestureSimulatorBinding (package:simulator/src/bindings/widgets_binding.dart)
#21     new SimulatorWidgetsFlutterBinding (package:simulator/src/bindings/widgets_binding.dart:32:9)
#22     SimulatorWidgetsFlutterBinding.ensureInitialized (package:simulator/src/bindings/widgets_binding.dart:37:17)
#23     main.<anonymous closure> (package:saber/main_simulated.dart:10:38)
#24     mainCommon (package:saber/main_common.dart:38:20)
#25     main (package:saber/main_simulated.dart:8:9)
#26     _runMain.<anonymous closure> (dart:ui/hooks.dart:301:23)
#27     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#28     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

Syncing files to device Linux...                                   101ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
```

**Comment by kekland** [comment]
Hi!

Unfortunately I don't have Linux installed on my end to test this out. Could you share the following info?
- Minimum reproducible code (e.g. try running this on the default Counter example, does it fail there)?
- OS version and Flutter version
- If possible, does this happen on Windows or macOS?

Thanks!

**Comment by adil192** [comment]
Yes this occurs on the `example` folder from this repo:
<details>
<summary>log</summary>

```console
ahann@fedora:~/Documents/GitHub/simulator/example$ flutter run -t lib/main.dart 
This app is using a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to migrate this app
to the V2 embedding.
Take a look at the docs for migrating an app:
https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects
Launching lib/main.dart on Linux in debug mode...
Building Linux application...                                           
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/rendering/object.dart': Failed assertion: line 1254 pos 16: 'onSemanticsUpdate != null': Attempted to enable semantics without configuring an onSemanticsUpdate callback.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      PipelineOwner._updateSemanticsOwner (package:flutter/src/rendering/object.dart:1254:16)
#3      PipelineOwner.attach (package:flutter/src/rendering/object.dart:1358:5)
#4      RendererBinding.initInstances (package:flutter/src/rendering/binding.dart:51:23)
#5      WidgetsBinding.initInstances (package:flutter/src/widgets/binding.dart:344:11)
#6      PointerListenerExtractorBinding.initInstances (package:simulator/src/bindings/pointer_listener_extractor.dart:11:11)
#7      AppImageExtractorBinding.initInstances (package:simulator/src/bindings/app_image_extractor.dart:11:11)
#8      MobileGestureSimulatorBinding.initInstances (package:simulator/src/bindings/mobile_gesture_simulator.dart:12:11)
#9      new BindingBase (package:flutter/src/foundation/binding.dart:154:5)
#10     new _SimulatorWidgetsFlutterBinding&BindingBase&GestureBinding (package:simulator/src/bindings/widgets_binding.dart)
#11     new _SimulatorWidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding (package:simulator/src/bindings/widgets_binding.dart)
#12     new _SimulatorWidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding (package:simulator/src/bindings/widgets_binding.dart)
#13     new _SimulatorWidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding&PaintingBinding (package:simulator/src/bindings/widgets_binding.dart)
#14     new _SimulatorWidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding&PaintingBinding&SemanticsBinding (package:simulator/src/bindings/widgets_binding.dart)
#15     new _SimulatorWidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding&PaintingBinding&SemanticsBinding&RendererBinding (package:simulator/src/bindings/widgets_binding.dart)
#16     new _SimulatorWidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding (package:simulator/src/bindings/widgets_binding.dart)
#17     new _SimulatorWidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding&PointerListenerExtractorBinding (package:simulator/src/bindings/widgets_binding.dart)
#18     new _SimulatorWidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding&PointerListenerExtractorBinding&SystemUiChromeExtractorBinding (package:simulator/src/bindings/widgets_binding.dart)
#19     new _SimulatorWidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding&PointerListenerExtractorBinding&SystemUiChromeExtractorBinding&AppImageExtractorBinding (package:simulator/src/bindings/widgets_binding.dart)
#20     new _SimulatorWidgetsFlutterBinding&BindingBase&GestureBinding&SchedulerBinding&ServicesBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding&PointerListenerExtractorBinding&SystemUiChromeExtractorBinding&AppImageExtractorBinding&MobileGestureSimulatorBinding (package:simulator/src/bindings/widgets_binding.dart)
#21     new SimulatorWidgetsFlutterBinding (package:simulator/src/bindings/widgets_binding.dart:32:9)
#22     SimulatorWidgetsFlutterBinding.ensureInitialized (package:simulator/src/bindings/widgets_binding.dart:37:17)
#23     runSimulatorApp (package:simulator/src/simulator_app.dart:26:50)
#24     main (package:example/main.dart:5:3)
#25     _runMain.<anonymous closure> (dart:ui/hooks.dart:301:23)
#26     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
#27     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

Syncing files to device Linux...                                   136ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available
interactive commands.
d Detach (terminate "flutter
run" but leave application
running).
c Clear the screen
q Quit (terminate the
application on the device).

A Dart VM Service on Linux is
available at:
http://127.0.0.1:41053/Yh1BigQU
pIQ=/

Application finished.
```
</details>

I'm running Fedora 40 Linux with Flutter 3.19.6:
<details>
<summary>flutter doctor -v</summary>

```console
ahann@fedora:~/Documents/GitHub/simulator/example$ flutter doctor -v
[✓] Flutter (Channel stable, 3.19.6, on Fedora Linux 40 (Workstation Edition)
    6.8.8-300.fc40.x86_64, locale en_GB.UTF-8)
    • Flutter version 3.19.6 on channel stable at /home/ahann/Documents/Sources/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (3 weeks ago), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for
      detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.


[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 18.1.1 (Fedora 18.1.1-1.fc40)
    • cmake version 3.28.2
    • ninja version 1.11.1
    • pkg-config version 2.1.0

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for
      detailed instructions).

[✓] VS Code (version 1.89.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.88.0

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Fedora Linux 40 (Workstation Edition)
      6.8.8-300.fc40.x86_64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 124.0.6367.118

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```
</details>

I'll try and get a Windows machine running to try this

**Comment by adil192** [comment]
Update: It runs fine on Windows 11 (on Flutter 3.19.6)
